### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Ardeshir81** [angular-ui/AngularJS-Atom#82]
HI! I just opened atom and saw an update is available to abgularJS package. I updated it. I restarted atom . and on (almost) every change to file, I get an error toaster:

![screenshot from 2017-12-02 20-39-44](https://user-images.githubusercontent.com/5755214/33517899-5eae6620-d7a1-11e7-8af4-bf96edf5e041.png)

Forget about the syntatic mistakes in screenshot. the errors and toasters appear even if no error exists.

[Enter steps to reproduce:]

1. Not Sure ... Just editing normal .js fiels would cause the issue
2. Mostly `'`, `,`, `{}` and other special characters would cause the issue and a toaster appear

**Atom**: 1.22.1 x64 (the issue existed on 1.21.1 too)
**Electron**: 1.6.15
**OS**: Linux Mint
**Thrown From**: [angularjs](https://github.com/angular-ui/AngularJS-Atom) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At /home/ardeshir81/.atom/packages/angularjs/lib/provider.coffee:104

TypeError: Cannot read property 'toLowerCase' of undefined
    at firstCharsEqual (/packages/angularjs/lib/provider.coffee:104:35)
    at Object.getJavascriptCompletions (/packages/angularjs/lib/provider.coffee:88:50)
    at Object.getSuggestions (/packages/angularjs/lib/provider.coffee:15:8)
    at providers.forEach.provider (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:262:21)
    at AutocompleteManager.findSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:254:23)
```

### Commands

```
     -4:12.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -2:07.9.0 application:reopen-project (div.tool-panel.tree-view)
     -1:59.5.0 command-palette:toggle (div.tool-panel.tree-view)
     -1:57.4.0 core:confirm (input.hidden-input)
     -1:57.3.0 platformio-ide-terminal:new (div.tool-panel.tree-view)
     -0:39.4.0 core:move-left (input.hidden-input)
     -0:37.5.0 intentions:highlight (input.hidden-input)
     -0:37.4.0 core:save (input.hidden-input)
  2x -0:20.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.5.0 
atom-beautify 0.30.9 
atom-ide-ui 0.6.0 
autoclose-html 0.23.0 
autocomplete-js-import 1.4.0 
busy-signal 1.4.3 
file-icons 2.1.14 
file-path-picker 0.2.0 
git-history 3.3.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
ide-typescript 0.7.0 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 2.0.0 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
teletype 0.1.2 
zentabs 0.8.9 
```

**Comment by rivermartinez** [comment]
I have the same error on Ubuntu 17.10

**Comment by outsideris** [comment]
I just released v0.5.1. Please check it out.

**Comment by Ardeshir81** [comment]
Just updated. Everything's Fine now ! 👍

**Comment by stanwmusic** [comment]
1.27.1 x64 I just purged and reinstalled newest version and it is  still happening on  Ubuntu 14.04 when I edit an HTML  button's text. :
I'm not worried about it, just letting you know in case it is useful. :-)

 /home/stan/.atom/packages/angularjs/lib/provider.coffee:127
Hide Stack Trace
TypeError: Cannot read property 'toLowerCase' of undefined
    at firstCharsEqual (/home/stan/.atom/packages/angularjs/lib/provider.coffee:127:10)
    at Object.getTagNameCompletions (/home/stan/.atom/packages/angularjs/lib/provider.coffee:94:66)
    at Object.getSuggestions (/home/stan/.atom/packages/angularjs/lib/provider.coffee:20:10)
    at providers.forEach.provider (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1792:32)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:996:18)
    at TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:2002:30)
    at mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:1429:25)
    at TextEditor.mergeSelections (/usr/share/atom/resources/app/src/text-editor.js:3416:53)
    at TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:3390:42)
    at TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:1428:23)
    at TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:1381:31)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/usr/share/atom/resources/app/src/text-editor-component.js:1661:30)

**Comment by stanwmusic** [comment]
![uncaught](https://user-images.githubusercontent.com/6845544/40575709-f83778a0-60b7-11e8-82ec-00227b03a43d.jpg)

**Comment by stanwmusic** [comment]
It just happened again after I just started newly installed Atom-beta and opened a website to edit.
![atom_errors-1](https://user-images.githubusercontent.com/6845544/43997925-9ecf1600-9db7-11e8-84c4-84499cd68652.jpg)
